language: python
python:
        - "2.6"
        - "2.7"
# command to install dependencies
install: 
        "pip install matplotlib"

# Solve the matplotlib DISPLAY error when trying
# to use a headless machine
before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"

# command to run tests
script: 
        - make test
